version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: puntored_postgres
    restart: always
    environment:
      POSTGRES_USER: user_node
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bd_puntored
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: